// Package schema defines the SchemaDefinition types that flow between the
// Schema Analysis phase (Phase 1) and the CodeAct code-generation phase
// (Phase 2).
package schema

import (
	"encoding/json"
	"fmt"
	"strings"
)

// ColumnSchema describes one column from the analysed CSV.
type ColumnSchema struct {
	// Name is the original CSV header.
	Name string `json:"name"`
	// GoType is the recommended Go type for this column.
	// Allowed values: "string", "int64", "float64", "decimal", "bool", "time.Time"
	GoType string `json:"goType"`
	// Validation is the validation rule to apply.
	// Allowed values: "none", "email", "url", "positive", "non-empty"
	Validation string `json:"validation"`
	// Description is a one-sentence semantic description generated by the LLM.
	Description string `json:"description"`
}

// SchemaDefinition is the AI-generated data contract returned by Phase 1.
type SchemaDefinition struct {
	// ResourceName is a singular, PascalCase name for the data entity (e.g. "Product").
	ResourceName string         `json:"resourceName"`
	Columns      []ColumnSchema `json:"columns"`
}

// ParseSchemaFromLLM extracts a JSON code block from raw LLM output and
// unmarshals it into a SchemaDefinition.  The LLM is expected to wrap its
// response in a ```json ... ``` fence.
func ParseSchemaFromLLM(raw string) (*SchemaDefinition, error) {
	// Strip markdown fences if present.
	cleaned := stripFences(raw, "json")
	if cleaned == "" {
		// Fall back to the raw text which might already be plain JSON.
		cleaned = strings.TrimSpace(raw)
	}

	var sd SchemaDefinition
	if err := json.Unmarshal([]byte(cleaned), &sd); err != nil {
		return nil, fmt.Errorf("schema: unmarshal SchemaDefinition: %w\nraw text was:\n%s", err, raw)
	}
	if sd.ResourceName == "" {
		return nil, fmt.Errorf("schema: missing resourceName in LLM response")
	}
	if len(sd.Columns) == 0 {
		return nil, fmt.Errorf("schema: LLM returned zero columns")
	}
	return &sd, nil
}

// ToJSON returns a pretty-printed JSON representation of the SchemaDefinition.
func (sd *SchemaDefinition) ToJSON() (string, error) {
	b, err := json.MarshalIndent(sd, "", "  ")
	if err != nil {
		return "", fmt.Errorf("schema: marshal: %w", err)
	}
	return string(b), nil
}

// stripFences removes the first ```<lang> ... ``` block from s and returns its
// content.  Returns an empty string if no such fence is found.
func stripFences(s, lang string) string {
	open := "```" + lang
	lines := strings.Split(s, "\n")
	var inside bool
	var result []string
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if !inside {
			if trimmed == open || trimmed == "```" {
				inside = true
			}
			continue
		}
		if trimmed == "```" {
			break
		}
		result = append(result, line)
	}
	return strings.TrimSpace(strings.Join(result, "\n"))
}
